### ISSUE TITLE
Color Labels + Dark Theme = unreadable filenames

### ISSUE THREAD

**Issue by a-tokarev** [elementary-tweaks/elementary-tweaks#105]
Dark Theme, no labels:

![no labels](https://user-images.githubusercontent.com/32895328/56851924-4c80fa80-691d-11e9-8a2c-b58f532a0d97.png)

Dark Theme with labels:
![with labels](https://user-images.githubusercontent.com/32895328/56851935-63bfe800-691d-11e9-9db8-7defd3744d80.png)

Suggestion: in Dark Theme, use dark font color for filenames on color labels.

(and thanks for Tweaks, by the way! It's excellent! :)

**Comment by ryonakano** [comment]
@a-tokarev I think you should submit this issue to [elementary/files](https://github.com/elementary/files)

**Comment by a-tokarev** [comment]
@ryonakano Thanks, but I seriously doubt that elementary OS devs will acknowledge the issue as related to elementary OS and therefore worthy to address. According to [one of them](https://github.com/elementary/files/issues/897#issuecomment-467967544), the system doesn't even have the Dark Mode (so why bother). Nevertheless I'll try to submit the issue to them, let's see what'll happen.

**Comment by ryonakano** [comment]
@a-tokarev Now you can close this one?

**Comment by a-tokarev** [comment]
Well, I did share my point here in Tweaks, and in elementary/files too. As I can't do anything else to fix the issue, let's close it )
