### ISSUE TITLE
Feature request: Add option to put file in desktop

### ISSUE THREAD

**Issue by bakeiro** [elementary-tweaks/elementary-tweaks#107]
ElementaryOs by default don´t include the option to have folders/files in the desktop (not sure why) can you please add this option in elementary tweaks?? 

thanks in advance :)

**Comment by ryonakano** [comment]
I'm not sure this is something we can enable or disable with some "switch" in elementary tweaks.

BTW there's an app called [Desktop Folder](https://appcenter.elementary.io/com.github.spheras.desktopfolder) that allows you to bring back the desktop.

**Comment by Philip-Scott** [comment]
Thank your for the suggestion, yes this is not something that we can control from a switch in tweaks. This is currently out of scope for this project and marking it as so
