### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by hugok79** [elementary-tweaks/elementary-tweaks#108]
Hello, Where can I do the translation of elementary-tweaks? The official method is
Launchpad? Or can i just download the .po file and translated it with poedit....
I'm a translator of Portuguese (pt) or (pt_PT)
Thanks in advanced.

**Comment by Philip-Scott** [comment]
Hello Hugo! 

I don't currently have a system or anything setup for translations, so basically just download the .po file for Portuguese and make a PR for it :) 

Thank you for your help!

**Comment by hugok79** [comment]
Ok. Thanks

**Comment by hugok79** [comment]
Hello Philip. it's done. see PR
