### ISSUE TITLE
Use more generic label for Cerbere

### ISSUE THREAD

**Issue by embik** [elementary-tweaks/elementary-tweaks#11]
I'm no big fan of using "Cerbere" as label for the corresponding pane. We should make tweaks as user-friendly as possible and the target audience does not know what Cerbere is. elementary OS tries to not expose code names to the users and we shouldn't either IMHO.

I'd propose "Watched processes" or something like that.

**Comment by Philip-Scott** [comment]
I agree :) maybe also put an info label with something like "watched processes will relaunch upon crash or exit" in the pane

Having my process being "watched" without knowing what for could feel a bit like a privacy concern

**Comment by embik** [comment]
Yes, we should add some small text snippet explaining the pane in more detail! That's a good idea. Maybe showing an infobar?

**Comment by Philip-Scott** [comment]
I don't think this is a job for an infobar.... What about the i info buttons that display a pop-over like the ones we use on the mouse plug? :)

**Comment by embik** [comment]
I have no Loki system available currently, would you mind to add a screenshot to make clear what you are referring to? :smile:

**Comment by Philip-Scott** [comment]
Like ![screenshot from 2016-03-28 07 11 16](https://cloud.githubusercontent.com/assets/10786508/14078601/4e19206a-f4b4-11e5-97d6-514517dbc771.png) :)

**Comment by Philip-Scott** [comment]
New Cerbere pane :smile: 
![screenshot from 2016-06-11 19 22 09](https://cloud.githubusercontent.com/assets/10786508/15988101/dc52de8a-3009-11e6-830b-04ee03b0e654.png)

**Comment by Philip-Scott** [comment]
Closing as there's no more Cerbere in Juno
