### ISSUE TITLE
Enable bold/semibold fonts

### ISSUE THREAD

**Issue by arguellesm** [elementary-tweaks/elementary-tweaks#111]
It seems that changing the default/document font to a bold or semibold one doesn't work properly. It does change the font type but not the weight. Instead of looking bold/semibold, it appears to be regular/thin. Its the same for both system and custom fonts.

**Comment by esda98** [comment]
Font style also seems to not work. All font modifications besides family and size seem to not function on Elementary Juno 5.0

**Comment by johnfactotum** [comment]
I don't think setting default font weight and style is currently supported by GTK. If you want to set font weight and style, you need to modify the [stylesheet](https://github.com/elementary/stylesheet).

From the [documentation](https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-font-name):`gtk-font-name` is the "default font to use. GTK+ uses the family name and size from this string." So everything other than family name and size is ignored.

**Comment by Philip-Scott** [comment]
Thank you for the info, @johnfactotum. I'll mark this as out of scope then :)
