### ISSUE TITLE
Changes in slingshot launcher are breaking Tweaks

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary-tweaks/elementary-tweaks#117]
As I can see, there are few changes in `io.elementary.desktop.wingpanel.application-menu` that may be responsible for tweaks not starting at all, producing these errors:
```
(io.elementary.switchboard:27813): Gtk-CRITICAL **: 20:22:26.931: gtk_combo_box_set_model: assertion 'GTK_IS_COMBO_BOX (combo_box)' failed
Max volume: 100

(io.elementary.switchboard:27813): GLib-GIO-ERROR **: 20:22:26.959: Settings schema 'io.elementary.desktop.wingpanel.applications-menu' does not contain a key named 'rows'
```
The trouble begun with slingshot-launcher v2.5.0. released 25th November 2019.

**Comment by calslate** [comment]
I'm experiencing this too. Glad to know it wasn't my fault it stopped working!

**Comment by GammaGames** [comment]
Duplicate of #115 that was closed a bit earlier than it should have

**Comment by marcelovbcfilho** [comment]
Same issue here...
`
(io.elementary.switchboard:10297): Gtk-CRITICAL **: 08:13:21.997: gtk_combo_box_set_model: assertion 'GTK_IS_COMBO_BOX (combo_box)' failed
Max volume: 100

(io.elementary.switchboard:10297): GLib-GIO-ERROR **: 08:13:22.033: Settings schema 'io.elementary.desktop.wingpanel.applications-menu' does not contain a key named 'rows'
`

**Comment by ryonakano** [comment]
Duplicate of #115

**Comment by ryonakano** [comment]
And this issue was fixed in #116, so we can close this issue.

**Comment by marcelovbcfilho** [comment]
> And this issue was fixed in #116, so we can close this issue.

Thanks

**Comment by ubgus** [comment]
I downloaded Tweaks for the first time yesterday, and I haven't been able to used, every time I try to open it, the setting apps crashed.
This is the first time I write an issue, so I don't know yet how can I be more helpful. This is what i found in the log file:
```io.elementary.s[3989]: gtk_combo_box_set_model: assertion 'GTK_IS_COMBO_BOX (combo_box)' failed
io.elementary.s[3989]: GtkSettings.vala:48: Error loading GTK+ Keyfile settings.ini: No existe el archivo o el directorio
io.elementary.s[3989]: GtkSettings.vala:69: Error getting GTK+ int setting: El archivo de claves no tiene el grupo «Settings»
io.elementary.s[3989]: Settings schema 'io.elementary.desktop.wingpanel.applications-menu' does not contain a key named 'rows'
kernel: [  126.758336] traps: io.elementary.s[3989] trap int3 ip:7f4a0ee99ea1 sp:7ffd7845cbd0 error:0 in libglib-2.0.so.0.5600.4[7f4a0ee48000+114000]
```
I tried to uninstall, reboot and reinstall, but the problem stay the same

**Comment by marcelovbcfilho** [comment]
> I downloaded Tweaks for the first time yesterday, and I haven't been able to used, every time I try to open it, the setting apps crashed.
> This is the first time I write an issue, so I don't know yet how can I be more helpful. This is what i found in the log file:
> 
> ```
> io.elementary.s[3989]: GtkSettings.vala:48: Error loading GTK+ Keyfile settings.ini: No existe el archivo o el directorio
> io.elementary.s[3989]: GtkSettings.vala:69: Error getting GTK+ int setting: El archivo de claves no tiene el grupo «Settings»
> io.elementary.s[3989]: Settings schema 'io.elementary.desktop.wingpanel.applications-menu' does not contain a key named 'rows'
> kernel: [  126.758336] traps: io.elementary.s[3989] trap int3 ip:7f4a0ee99ea1 sp:7ffd7845cbd0 error:0 in libglib-2.0.so.0.5600.4[7f4a0ee48000+114000]
> ```
> 
> I tried to uninstall, reboot and reinstall, but the problem stays the same

The PPA version is not updated, build the git repository and it will run.

**Comment by ubgus** [comment]
Oh! got it. Thank you.

**Comment by Philip-Scott** [comment]
Looks like the github automatic import for the PPA has been failing since `2019-02-08` ... I just triggered a manual upload over at https://code.launchpad.net/~philip.scott/elementary-tweaks/github/+index, so hopefully that will work

**Comment by GammaGames** [comment]
I don’t see any new version yet, did that also fail?

**Comment by ryonakano** [comment]
@Philip-Scott According to [this answer](https://askubuntu.com/questions/1154040/ppa-package-update-throwing-invalid-sha-on-import), that issue might be due to cross-synchronization between bzr and git. And indeed your branch on Launchpad uses bzr, while the one on GitHub uses git. So, what about creating a new branch that uses git, copy the recipe, and link that branch to the PPA?

**Comment by Philip-Scott** [comment]
Sorry, I've been AFK this week due to Thanksgiving, I'll try to make the new recipe and everything one again :)

**Comment by Philip-Scott** [comment]
Alright, the build has been successful and the PPA was updated. People should be getting the updates throughout the day as the package goes to the mirrors :) Let me know if there are any other problems with the update

https://code.launchpad.net/~philip.scott/+archive/ubuntu/elementary-tweaks

**Comment by WebShapedBiz** [comment]
Thank you @Philip-Scott for your time and effort.
