### ISSUE TITLE
Cannot install elementary-tweaks from an Elementary OS Hera fresh install.

### ISSUE THREAD

**Issue by noesmeteoro** [elementary-tweaks/elementary-tweaks#123]
Seems like a PPA problem. 

user@pc:~$ sudo add-apt-repository ppa:philip.scott/elementary-tweaks
[sudo] password for user:
Cannot add PPA: 'ppa:~philip.scott/ubuntu/elementary-tweaks'.
ERROR: '~philip.scott' user or team does not exist.

sources.list and apt.conf.d/*.conf repos by default.

behind a proxy but already configured in apt.conf:

Acquire::http::Proxy "http://user:passwd@proxy:proxyport/";

thanks in advance.

**Comment by ryonakano** [comment]
I can't confirm this issue, I suppose it might be a network problem on your side (or Launchpad).
Are you constantly facing this issue?

**Comment by noesmeteoro** [comment]
Hi! Thanks for the answer. 
Confirmed, problem was mine. I ran "export http_proxy= ...." badly.
Thank you again!

**Comment by noesmeteoro** [comment]
Hi! Thanks for the answer.
Confirmed, problem was mine. I ran "export http_proxy= ...." badly.
Thank you again!
