### ISSUE TITLE
Window Layout not changing for non elementary apps

### ISSUE THREAD

**Issue by artistro08** [elementary-tweaks/elementary-tweaks#126]
I'm not sure if this is a dconf issue, or an elementary issue, but when I switch the window layout, it doesn't stick for some windows. Electron wrappers mostly

**Comment by ryonakano** [comment]
This is a duplicate of #122 and was fixed in #124.

The fix should have already been released. Is your system up to date? Did you installed elementary Tweaks from the PPA by Felipe Escoto, whose development has been still continued?

**Comment by artistro08** [comment]
No I haven't. Thanks! Closing this.
