### ISSUE TITLE
Enable builds for Odin (Focal)

### ISSUE THREAD

**Issue by ryonakano** [elementary-tweaks/elementary-tweaks#127]
![Screenshot from 2020-01-28 19-39-23](https://user-images.githubusercontent.com/26003928/73256788-edcb1300-4205-11ea-9ff2-6f2e76162b33.png)

(The screenshot above is one of my recipes on Launchpad)

The next version of elementary OS should be based on Ubuntu 20.04 LTS. We don't have to address this issue anytime soon but we need to add `Focal` to the "Distribution series" at [here](https://code.launchpad.net/~philip.scott/+recipe/elementary-tweaks-daily-git) so that users can install elementary Tweaks on the next version of elementary OS.

**Comment by Philip-Scott** [comment]
I've added Focal to the Distribution series and kicked off a build. Looks like it build correctly for Focal

**Comment by ryonakano** [comment]
Glad to hear that, thank you very much!
