### ISSUE TITLE
Not overriding stylesheet on Mail app

### ISSUE THREAD

**Issue by KorbsStudio** [elementary-tweaks/elementary-tweaks#128]
![image](https://imgur.com/upBduBl.png)
Appears when enabling the "Prefer Dark Variant" option in the appearance settings of Tweaks, the Mail app is still using a light theme.

**Comment by ryonakano** [comment]
I can't confirm your issue. Did you try restarting Mail/logging out from the current session/rebooting your system?

**Comment by KorbsStudio** [comment]
Restarting the session worked, just noticed the uptime is 3 days.
