### ISSUE TITLE
Terminal splitting tab window

### ISSUE THREAD

**Issue by Globegitter** [elementary-tweaks/elementary-tweaks#13]
I am not sure if that might be an overkill for elementary tweaks and I really think this should be a basic feature, but would it be possible to this at the very least in elementary tweaks? Ref: https://bugs.launchpad.net/pantheon-terminal/+bug/1217515

**Comment by embik** [comment]
I actually don't think this can be implemented with elementary-tweaks because tweaks is basically just exposing dconf keys for elementary applications. If the setting is not present in the Pantheon Terminal codebase, it cannot be activated through tweaks.

**Comment by Philip-Scott** [comment]
Yup, Embik is correct, it cannot be done without modifying the code of pantheon-terminal.
