### ISSUE TITLE
Broken maximizing option and abnormal minimum window size.

### ISSUE THREAD

**Issue by younyokel** [elementary-tweaks/elementary-tweaks#130]
Hey, I reinstalled my system because of problems and I didn't really know why it was happening before but now it turns out that THIS application breaks some programs' ability to maximize the window and also sets a weird minimum size value like default settings app or maybe more.

Maybe someone already talked about this, but anyway, this can be fixed by removing the application after changing whatever you needed to change using `sudo apt remove elementary-tweaks`. Changes you've made will never reset.

Thank you.

**Comment by Philip-Scott** [comment]
What types of breaks were you getting, the app does nothing to set any min sizes or anything like that. Please file an issue https://github.com/pantheon-tweaks/pantheon-tweaks/issues if you have any more information, thank you
