### ISSUE TITLE
Make a 1.0.1 release

### ISSUE THREAD

**Issue by a-mere-peasant** [elementary-tweaks/elementary-tweaks#131]
Could someone please draft a 1.0.1 release , the 0.0.1 is really old and meant for eos "Loki". I'm packaging for fedora and would like for a new release to be drafted . 
Thanks

**Comment by LinArcX** [comment]
I'm providing elementary-tweaks for void-linux. Please release new version.

**Comment by a-mere-peasant** [comment]
hey @LinArcX I'm currently using the latest commit to package this , you might want to do the same until a new release is made , or maybe just fork this and make a release yourself and use that for packaging for the time being.

**Comment by LinArcX** [comment]
@a-mere-peasant Hi. actually i don't have any problem for personal usage. But void-linux team only accept released versions.

**Comment by Philip-Scott** [comment]
Made a new release :) Thank you everyone for creating the packages
