### ISSUE TITLE
Apply the "Prefer dark variant" to App Center

### ISSUE THREAD

**Issue by KorbsStudio** [elementary-tweaks/elementary-tweaks#134]
When dark variant is enabled, the App Center still have a light theme to it: 
![image](https://imgur.com/Dsjsj0w.png)

**Comment by ryonakano** [comment]
AppCenter is always running in the background from when you log in and until you log out so that it can fetch updates. As a consequence, changing to the dark variant does not take effect to AppCenter until you log out or reboot your system.
