### ISSUE TITLE
💡: Pitch black - dark mode option

### ISSUE THREAD

**Issue by joe733** [elementary-tweaks/elementary-tweaks#141]
It would be good if we had a pitch black (or as twitter calls it "lights-out") version of dark theme:

![Screenshot from 2020-04-09 11-18-28](https://user-images.githubusercontent.com/38415384/78862001-eb7e0400-7a53-11ea-8375-bafd66b1ccf1.png)

The title bar does not blend in...

**Comment by ryonakano** [comment]
elementary Tweaks only switches available themes in your system. Creating a new theme is out of scope for it. I'm not sure if elementary developers accept it, but I guess you may want to submit your feature request at https://github.com/elementary/stylesheet.

**Comment by joe733** [comment]
> Creating a new theme is out of scope for it. I'm not sure if elementary developers accept it, but I guess you may want to submit your feature request at https://github.com/elementary/stylesheet.

Okay.

> Elementary Tweaks only switches available themes in your system

Oh the current dark mode is already available in my system, can you please tell where is it in dconf (I searched but could not find it)?

**Comment by ryonakano** [comment]
![2020-04-09 16 15 45 のスクリーンショット](https://user-images.githubusercontent.com/26003928/78868180-6b6c9400-7a7d-11ea-898a-36ea0f242aac.png)

I haven't used any custom themes on elementary OS, but I guess you can switch from Appearance Pane→Theme Settings→GTK+. If you have installed theme files in `~/.local/share/themes/`, the theme name should appear in this combobox.

**Comment by joe733** [comment]
> ![2020-04-09 16 15 45 のスクリーンショット](https://user-images.githubusercontent.com/26003928/78868180-6b6c9400-7a7d-11ea-898a-36ea0f242aac.png)
> 
> I haven't used any custom themes on elementary OS, but I guess you can switch from Appearance Pane→Theme Settings→GTK+. If you have installed theme files in `~/.local/share/themes/`, the theme name should appear in this combobox.

@ryonakano I'm not using any GTK+ theme either, I was just asking about the <kbd>toggle switch</kbd> `Prefer dark variant`, how can I switch that <kbd>on</kbd> via `terminal`? or from the `dconf-editor`?

![Screenshot from 2020-04-09 17-15-27](https://user-images.githubusercontent.com/38415384/78891975-1da85980-7a86-11ea-8ea1-c33bfb17fd64.jpg)

**Comment by a-mere-peasant** [comment]
@joe733  the themes are available at ~/.themes or usr/share/themes you might want to check there ,if you find a suitable theme instead , just copy it to .themes and switch using the tweaks . As for the toggle switch , I have no idea how to use it from terminal .Is there a reason for not using the tweaks gui ?

**Comment by ryonakano** [comment]
The "Prefer dark variant" switch only toggles between two options―light theme and dark theme. Even if you use Terminal or Dconf Editor, you can't switch to another option "pitch black".

(BTW, the "Prefer dark variant" setting is saved in `/home/ryo/.config/gtk-3.0/settings.ini`. The number next to `gtk-application-prefer-dark-theme` represents saved setting.)

**Comment by joe733** [comment]
> @joe733 the themes are available at ~/.themes or usr/share/themes you might want to check there, if you find a suitable theme instead, just copy it to .themes and switch using the tweaks.

Yeah I know that well.

> Is there a reason for not using the tweaks gui ?

I kind of don't want PPAs on my system.

> Even if you use Terminal or Dconf Editor, you can't switch to another option "pitch black".

Yeah I understand.

> (BTW, the "Prefer dark variant" setting is saved in /home/ryo/.config/gtk-3.0/settings.ini. The number next to gtk-application-prefer-dark-theme represents saved setting.)

Thanks.

---

Okay, I'm closing this issue as it is <kbd>out-of-scope</kbd> for this repository.

**Comment by a-mere-peasant** [comment]
@joe733  if you don't want to use the ppa , maybe just build it locally . There are a few guides for doing this on fedora 30 and I don't think that a lot of change would be required to build for ubuntu based systems
