### ISSUE TITLE
New Settings update - Dark Varient not working on settings

### ISSUE THREAD

**Issue by KorbsStudio** [elementary-tweaks/elementary-tweaks#146]
![image](https://i.imgur.com/WfG326I.png)
Elementary OS just got a new [update](https://blog.elementary.io/hera-updates-for-april-2020/) to the settings today and with that I guess they must of updated something where the dark variant option doesn't work on Settings anymore.

________________________________________

**Update**: This issue will be closed when Elementary OS 6.0 comes out, which will finally feature dark mode in the native settings. 
Preview of new Greeter: 
<img width="425" src="https://pbs.twimg.com/media/Ebnw0KyU4AAaolE?format=jpg&name=medium">

**Comment by harunyasar** [comment]
Same here. It would be great if someone fixed this before I go blind :laughing:

**Comment by KorbsStudio** [comment]
Haha yeah. The update was very recent, so I guess we shouldn't expect a fix too soon.

**Comment by wedsonlopes** [comment]
I also got the same issue here.

**Comment by ryonakano** [comment]
![Screenshot from 2020-05-01 21-20-33](https://user-images.githubusercontent.com/26003928/80805128-20fcb400-8bf2-11ea-8477-80904abd6eff.png)

This is because System Settings now follows system dark style preference which is configurable from Desktop→Appearance only when  (see [this commit](https://github.com/elementary/switchboard/commit/636d2ff4c88dfec9389984b71004632f89d93793). Specifically, [this line](https://github.com/elementary/switchboard/blob/636d2ff4c88dfec9389984b71004632f89d93793/src/Application.vala#L143) causes this issue. It overrides the value and thus only System Settings uses the light style even if we set `gtk_settings.gtk_application_prefer_dark_theme` to `true` to enable the dark style system widely in elementary Tweaks.

**Comment by ryonakano** [comment]
I dug into this issue and found the consequence of selecting "Dark" in Desktop Plug and "Prefer dark variant" in elementary Tweaks is different. The latter saves the following content to `~/.config/gtk-3.0/settings.ini`:

```
[Settings]
gtk-application-prefer-dark-theme=0
```

and this forces all apps to use dark style.

On the other hand, the former just saves whether a user wants light style or dark style. And then, only apps that can detect this selection set the value of `gtk-application-prefer-dark-theme` depends on this selection; that is, the former one is a kind of per-app setting, although it looks OS-wide setting. Maybe this is similar to the dark preference of Android or iOS.

So, only choosing "Dark" in Desktop Plug does not make apps that can't detect this selection like Google Chrome or Slack to use dark style. If you want to force these apps to use dark style, you also still need to enable "Prefer dark variant" in elementary Tweaks.

**Comment by harunyasar** [comment]
@ryonakano, I followed your conclusions and almost everything has turned into dark except Switchboard itself. Thank you!

**Comment by ibnumardini** [comment]
![image_2020-05-27_08-30-22](https://user-images.githubusercontent.com/52898834/82966169-5ed3d900-9ff4-11ea-85a6-4db4659c0ad4.png)

 i have same problem :(

**Comment by BananaManCJ** [comment]
It displays as dark if you run ```GTK_THEME=elementary:dark io.elementary.switchboard```

**Comment by yunusemredilber** [comment]
With the latest update, most of the components stopped working with the dark variant.
![Screenshot from 2020-06-20 12-47-51](https://user-images.githubusercontent.com/46731483/85198863-52415880-b2f4-11ea-9361-774e87be6e56.png)

**Comment by ryonakano** [comment]
So from now on, any official components of elementary (like Wingpanel) and default apps will support the new OS-wide dark style preference. And this (official) dark style preference does not have compatibility with the current (unofficial) dark variant. This is the reason why many components get to be changed to the light style despite the "Prefer dark" settings in elementary Tweaks. Don't worry, these components will follow your style selection again on the next version of elementary OS (but its setting page is in Desktop Plug, no longer in elementary Tweaks). For now, we need to be patient though.

**Comment by yunusemredilber** [comment]
> So from now on, any official components of elementary (like Wingpanel) and default apps will support the new OS-wide dark style preference (which is not available on Hera). And this (official) dark style preference does not have compatibility with the current (unofficial) dark variant. This is the reason why many components get to be changed to the light style despite the "Prefer dark" settings in elementary Tweaks. Don't worry, these components will follow your style selection again on the next version of elementary OS (but its setting page is in Desktop Plug, no longer in elementary Tweaks). For now, we need to be patient though.

Thanks for the explanation @ryonakano :+1:

**Comment by onsah** [comment]
@BananaManCJ it works when I launch from the terminal, but it doesn't work when opened from another terminal or from the dock. Is there a way to apply to the whole system from terminal?

**Comment by BananaManCJ** [comment]
> @BananaManCJ it works when I launch from the terminal, but it doesn't work when opened from another terminal or from the dock. Is there a way to apply to the whole system from terminal?

@onsah you can add ```export GTK_THEME=elementary:dark``` to the end of your ~/.profile file and restart lightdm

**Comment by mrHovhannisyan** [comment]
> It displays as dark if you run `GTK_THEME=elementary:dark io.elementary.switchboard`

After running the command, I get the following error "(io.elementary.switchboard:24585): Gtk-CRITICAL **: 22:13:02.096: gtk_entry_get_text: assertion 'GTK_IS_ENTRY (entry)' failed" and it turned back to light

**Comment by KorbsStudio** [comment]
I went ahead and created a script to modify the `.desktop` file.
Easy and quick install:
```
bash <(wget -qO- https://raw.githubusercontent.com/KorbsStudio/elementary-settings-dark-mode-fix/master/install-dark-mode-into-settings.sh)
```
Preview after install:
![GIF](https://i.imgur.com/TGy9qm5.gif)

If something goes wrong or isn't right, create an issue here: https://github.com/KorbsStudio/elementary-settings-dark-mode-fix/issues
