### ISSUE TITLE
Please rename 🙏️

### ISSUE THREAD

**Issue by cassidyjames** [elementary-tweaks/elementary-tweaks#149]
We still have people assuming "elementary Tweaks" is an official, supported thing. It would probably make sense to rename the org and project to `pantheon-tweaks` since it's not anything from elementary, but is designed for Pantheon.

**Comment by Philip-Scott** [comment]
Sounds reasonable. I created [pantheon-tweaks](https://github.com/pantheon-tweaks) for now, but instead of renaming this org I'll just make everything here point to there to avoid having someone else take control of the name and all of the legacy links.

**Comment by Philip-Scott** [comment]
Now tracked under https://github.com/elementary-tweaks/elementary-tweaks/projects/1

**Comment by cassidyjames** [comment]
Thanks, @Philip-Scott!
