### ISSUE TITLE
Settings crash on start, terminal settings don't contain key 'opacity'

### ISSUE THREAD

**Issue by bbjansen** [elementary-tweaks/elementary-tweaks#18]
When installing Elementary Tweaks on the latest version of Loki Beta released on elementary.io/developer it gives the following error when launching switchboard:

`[ERROR 03:25:32.120469] [GLib-GIO] Settings schema 'org.pantheon.terminal.settings' does not contain a key named 'opacity'
`

**Comment by Philip-Scott** [comment]
Mmmm did you install the PPA? Because the reason we created this branch was due to Elementary Tweaks crashing for that problem, and the line is even commented out :wink:  (https://github.com/elementary-tweaks/elementary-tweaks/blob/master/src/Settings/TerminalSettings.vala#L26)

**Comment by bbjansen** [comment]
You were right. I don't know how (must have had the wrong PPA on my clipboard), but added an outdated PPA. Works now! My bad ;).
