### ISSUE TITLE
Make the tweak-tool look more "elementary"

### ISSUE THREAD

**Issue by Philip-Scott** [elementary-tweaks/elementary-tweaks#2]
The current tweak tool uses granite's sidebar for switching between categories. We should make it look more like the accessibility settings plug

![screenshot from 2016-03-13 12 34 11](https://cloud.githubusercontent.com/assets/10786508/13730549/ebd3dee2-e917-11e5-9916-6ce507cd986e.png)

**Comment by embik** [comment]
Some bullet points to make this happen:
- [ ] Deprecate `Granite.Widgets.ThinPaned` and use `Gtk.Paned`
- [ ] Deprecate `Granite.Widgets.SourceLis` and use `Gtk.ListBox`
- [ ] Use a different size for icons (`Gtk.IconSize.DND`)
- [ ] Use `Gtk.Frame`, `Gtk.ListBox` and `Gtk.Separator` to build settings keys

We should also investigate how much of this is possible on Freya for backporting purposes. I feel like v1.1 really should support Freya to get people to use it.

**Comment by Philip-Scott** [comment]
iirc, i made the a11y plug under freya, so everything should be possible :)

 I'll take care of that this week
