### ISSUE TITLE
Suggestion: Don't use add-apt-repository

### ISSUE THREAD

**Issue by Maccer1** [elementary-tweaks/elementary-tweaks#20]
add-apt-repository is no longer in elementaryOS by default. It'd be great if you updated the readme and used another method.

**Comment by varlesh** [comment]
You like this? 
```
wget package
dpkg -i package
```

**Comment by Philip-Scott** [comment]
The wget method works, but I personally would like a way to have it installed and add a PPA on it for updates and such...... I think there is a way to make it so a .deb installs a PPA, but i'll have to look into it

**Comment by png2378** [comment]
What do you think about bash-script like here? `wget -O - domain.com/tweaks.sh | bash`

The script can be added repo in sources list and PPA’s public key.

**Comment by NicoHood** [comment]
Ahm....? What about installing add-apt the normal way? As I understood it, it is just not installed by default, but you can always reinstall it later. So I see no problem at all!?

**Comment by Philip-Scott** [comment]
Honestly, i think every other way of installing the PPA would just be against the reason of why it got removed on the first place (Security reasons) and i also don't think that we should get people used to things like `wget script.sh` as a script could even be more dangerous in the wrong hands....

**Comment by NicoHood** [comment]
it is ALWAYS a security risk to install third party software without checking signatures and checking the source. It was removed, so people who install those ppas are aware of this. add-apt was made for such things. I suggest to just keep things as they are and probably add a small hint on how to install the ppa. Then people should go and read about those security risks. They also have to do this for every other ppa and other maintainers will not change their instructions just because EOS does not have this installed by default. I do not even know if other OS have this installed by default. Its like on arch: know what you are doing. And if you just install its your fault. A script would not solve this in any way.

**Comment by Maccer1** [comment]
So what If you just create a .deb without any updating mechanism? At first it may not be a good idea because the app is constantly updated but after a while I remember that elementary-tweaks for Freya was barely updated so it won't really matter, I think.

Or you could maybe create some sort of notification so that when there's a new update you ask them to download the new version.

**Comment by embik** [comment]
@Maccer1 that feels like you just throw all the advantages package mangement offers overboard. If we're talking about "teaching" users, even the `wget` approach seems to be better than just offering a raw .deb package (IMHO).

**Comment by NicoHood** [comment]
It is just one google search away:
https://askubuntu.com/questions/493460/how-to-install-add-apt-repository-using-the-terminal

I do not think anything has to be changed at all.

**Comment by henriquearthur** [comment]
T

**Comment by Philip-Scott** [comment]
@henriquearthur Sadly, for this app to be in the AppStore it would need to either be in the official Ubuntu repos, or in the official elementary repo, and non of those would likely ever happen.... You can also make it appear there after you add the ppa, but that also means having to `add-apt-repository` :/

**Comment by apcamargo** [comment]
The inclusion in AppCenter without being in the Ubuntu respos will be possible soon with Houston. From what I know, it will be launch soon

**Comment by Shackelford-Arden** [comment]
I may lack an understanding of "the finer" things here but... could you not simply instruct users to manually create the repo file? Then simply apt update and presto! You can apt install tweaks now. No need to install add-apt-repository.

**Comment by Philip-Scott** [comment]
@Shackelford-Arden It's not that easy... There is a key that also needs to be added, which is done automatically with add-apt-repository

**Comment by Shackelford-Arden** [comment]
Is there not a way to do that by hand as well? I mean... I'd love to have it automated just as much as the next person but not having to worry about a dependency is sometimes just a nice.

**Comment by OriginalFannibal** [comment]
Now that the AppCenter is here, any chance of getting this on it? I am sure a lot of people would really appreciate it there.

**Comment by Philip-Scott** [comment]
@OriginalFannibal See https://github.com/elementary-tweaks/elementary-tweaks/issues/48#issuecomment-306370803 for the reasons :)

**Comment by michaelkanis** [comment]
Some other programs (e. g. Chrome IIRC) just put a .list file into /etc/apt/sources.list.d/ inside the deb. That way you can simply install the deb and it will also auto-update without having to add the ppa manually via command line.
I am not sure if this is a good idea, though. 🤷

**Comment by Philip-Scott** [comment]
Closing since it's now being tracked over at the other project.
