### ISSUE TITLE
Tweaks on Loki Beta crashes Wingpanel and Switchboard

### ISSUE THREAD

**Issue by thementalgoose** [elementary-tweaks/elementary-tweaks#22]
Installing elementary tweaks via. the PPA and the `make` method in the Loki Beta causes wingpanel and switchboard to crash. Terminal output says there's no such key `opacity` in `org.pantheon.terminal.settings`. 

#### Quick Workaround

A little workaround is to change the schemas so that an opacity key is contained, even if it doesn't do anything for the terminal 

Open in a text editor or *nano* with **root**: `/usr/share/glib-2.0/schemas/org.pantheon.terminal.gschema.xml`, and contained within the `org.pantheon.terminal.settings` schema paste an "opacity" key

```xml
<schema path="/org/pantheon/terminal/settings/" id="org.pantheon.terminal.settings"
  gettext-domain="pantheon-terminal">
  <!-- ......keys...... -->
  <!-- ......more keys...... -->
  <!-- ......a few more keys...... -->
  
  <key name="opacity" type="i">
    <default>90</default>
    <summary>Opacity</summary>
    <description>How transparent the terminal is</description>
  </key>
</schema> 
```

Then you need to reinstall the libs so that the schema is rebuild

```bash
sudo apt-get update
sudo apt-get install --reinstall libglib2.0-dev
```

This removes the error and gives access to some (not all) of the other tweaks available, my guess is those that are currently supported. But at least it now loads :+1:

**Comment by Philip-Scott** [comment]
Are you sure you installed the correct version and not from another repo? #18 :wink:

**Comment by thementalgoose** [comment]
Well crap.. I did try another PPA but im pretty sure I removed it :S I'll check in a second

**Comment by Philip-Scott** [comment]
Don't worry :smile:  I really want the last maintainer to remove the loki build from his PPA since google still shows his branch higher up

**Comment by thementalgoose** [comment]
That sounds good to me 👍  I do think this needs to be on the README as well though, just because when the issue is marked as invalid it becomes more difficult to find, hence I didn't find it initially 👍
