### ISSUE TITLE
Tweaks crashes if audience is not installed

### ISSUE THREAD

**Issue by png2378** [elementary-tweaks/elementary-tweaks#23]
Tweaks crashes with error `[GLib-GIO] Settings schema 'org.pantheon.audience' is not installed`.

**Comment by dza89** [comment]
Confirmed.

**Comment by Philip-Scott** [comment]
Woops, i completely forgot about this issue.... the latest commit (d55163a785fbfaf909df71d781ce3b0a21536002) should've fixed this and future issues of this kind :)
