### ISSUE TITLE
Videos: stay on top doesn't work

### ISSUE THREAD

**Issue by png2378** [elementary-tweaks/elementary-tweaks#25]
Option "Stay on top while playing" doesn't work.

**Comment by Philip-Scott** [comment]
Mmm... the correct settings key is being toggled, so it might be an Audience bug :/ I do remember it working not too long ago

**Comment by png2378** [comment]
@Philip-Scott, this key works for you now?

**Comment by Philip-Scott** [comment]
not at the moment, i'm going to comment the code for this for now
