### ISSUE TITLE
Feature request: keyboard pane

### ISSUE THREAD

**Issue by png2378** [elementary-tweaks/elementary-tweaks#27]
Keyboard settings will be useful for many users. 

We can place there "[Super key run Launcher](http://elementaryos.stackexchange.com/a/2083/160)" option and some xkb-options, because Options tab [removed](http://bazaar.launchpad.net/~elementary-pantheon/switchboard-plug-keyboard/trunk/revision/433) from keyboard plugin.

**Comment by ryonakano** [comment]
![screenshot](https://user-images.githubusercontent.com/26003928/73143474-b2352980-40dd-11ea-802e-d16e25d60509.png)

I don't think we'll need to create a keyboard pane in elementary Tweaks because now that Switchboard Keyboard Pane officially supports setting Super key to open Launcher.

**Comment by Philip-Scott** [comment]
Closign as the default keybaord pane on elementary contains this setting now :)
