### ISSUE TITLE
Why so complicated?

### ISSUE THREAD

**Issue by eprozium** [elementary-tweaks/elementary-tweaks#31]
Hi,

eOS seems to be all about ease of use and getting new users from other platforms.

Why is so complicated  the install procedure for this essential tool?

Wouldn't be much easier if it were in the "App Store"? There are already "teak tools" in there, but not this one :(.

Thank you.

**Comment by Philip-Scott** [comment]
Sadly, for this app to be in the AppStore it would need to either be in the official Ubuntu repos, or in the official elementary repo, and non of those would ever happen....

Elementary tweaks is also not something meant for every user should install, it's more for the advanced users who want to use elementary and also tweak their system to their liking :) So i think having those 3 commands is easier than the alternatives

**Comment by eprozium** [comment]
> Elementary tweaks is also not something meant for every user should install, it's more for the advanced users who want to use elementary and also tweak their system to their liking :) 

Looking what can (and should) be change-able, I would say they're totally for the average user.
The advanced user will have no problem tweaking the system even without a config UI.
