### ISSUE TITLE
Add setting for hDPI!

### ISSUE THREAD

**Issue by eprozium** [elementary-tweaks/elementary-tweaks#32]
Even if Loki is supposed to support "hDPI" and a the "keynote" advertises it, there's no way for the users to set/change/fix if the "automatic" stuff does not get it :(.

So the user is left again with "gsettings", but this is something most users coming from other platforms won't do.

Thank you.

**Comment by apcamargo** [comment]
Maybe a option to choose the _scaling-factor_ could be added in the 'Appearance' section

**Comment by Philip-Scott** [comment]
@eprozium did it not get your's automatically? This might be something that should be fixed upstream if it's not detecting your screen correctly

**Comment by ryonakano** [comment]
![2018-07-28 16 43 01](https://user-images.githubusercontent.com/26003928/43354347-6ffd2584-9285-11e8-850a-7e266f0ba604.png)

Now I don't think we have to add this option to elementary-tweaks since in Juno switchboard-display-plug has it.
