### ISSUE TITLE
Feature request: add an option to turn on/off the transparency in Terminal

### ISSUE THREAD

**Issue by apcamargo** [elementary-tweaks/elementary-tweaks#35]
In terminal, this can be achieved with:
`gsettings set org.pantheon.terminal.settings background "rgba(37, 46, 50, 1)"`

**Comment by Philip-Scott** [comment]
You can also do this by setting the background color to a solid one :wink:

**Comment by apcamargo** [comment]
Yeah, but there's no easy way to do this currently :(

**Comment by a-tokarev** [comment]
> In terminal, this can be achieved with:
> gsettings set org.pantheon.terminal.settings background "rgba(37, 46, 50, 1)"

Tried that. Terminal said:
`No such schema “org.pantheon.terminal.settings”`

**Comment by Philip-Scott** [comment]
Closing since there is an active workaround to do this, and there is not an actual setting to flip on the pantheon-terminal
