### ISSUE TITLE
Error: It doesn't work

### ISSUE THREAD

**Issue by pedrotarazi** [elementary-tweaks/elementary-tweaks#36]
Hi. Sorry for my english. I'm from Argentina. I have a problema with Tweaks. 
When I installed Tweaks, I can't to enter en the System Settings, the top bar blinks, the Slingshot doesn't open. 
When I uninstalled Tweaks, everything works normally.

Link video error: https://www.youtube.com/watch?v=iYMOnJc4Dmw
Photo when I uninstal Tweaks: https://fotos.subefotos.com/b437819c3fb529c55ebfb04a1b7170c8o.jpg

PC Specifications:
Toshiba Satellite L845 4105SP
Intel Core i7 3236Q
RAM Memory 8GB
Video Memori 1GB Radeon HD 7600M Series
Windows10 and Elementary OS

Regards! Thanks!

**Comment by Philip-Scott** [comment]
Hey Pedro! :) 

Do you get anything on your terminal when you try to run switchboard (the system settings) from the terminal?

**Comment by pedrotarazi** [comment]
**pedrotarazi@pedroOS:~$** switchboard -d
[INFO 16:30:23.207354] Application.vala:155: System Settings version: 2.0
[INFO 16:30:23.207395] Application.vala:157: Kernel version: 4.4.0-47-generic
[DEBUG 16:30:23.208542] [Gtk] Connecting to session manager
[DEBUG 16:30:23.211575] DisplayPlug.vala:211: Activating Display plug
[DEBUG 16:30:23.211676] PlugsManager.vala:91: pantheon-display registered
[DEBUG 16:30:23.212415] ColorPlug.vala:92: Activating Color plug
[DEBUG 16:30:23.212502] PlugsManager.vala:91: hardware-gcc-color registered
[DEBUG 16:30:23.213080] SoundPlug.vala:142: Activating Sound plug
[DEBUG 16:30:23.213134] PlugsManager.vala:91: hardware-gcc-sound registered
[DEBUG 16:30:23.213702] WacomPlug.vala:92: Activating Wacom plug
[DEBUG 16:30:23.213755] PlugsManager.vala:91: hardware-gcc-wacom registered
[DEBUG 16:30:23.214422] keyboard.vala:51: Activating Keyboard plug
[DEBUG 16:30:23.214492] PlugsManager.vala:91: hardware-pantheon-keyboard registered
[DEBUG 16:30:23.215209] mouse-touchpad.vala:130: Activating Mouse-Touchpad plug
[DEBUG 16:30:23.215313] PlugsManager.vala:91: pantheon-mouse-touchpad registered
[DEBUG 16:30:23.216036] Plug.vala:388: Activating Power plug
[DEBUG 16:30:23.219350] Battery.vala:72: it is a dekstop (laptops false)
[DEBUG 16:30:23.222098] PowerSupply.vala:58: power supply path: (null) dbus connected

** (process:12337): CRITICAL **: string_contains: assertion 'self != NULL' failed

** (process:12337): CRITICAL **: string_contains: assertion 'self != NULL' failed
[DEBUG 16:30:23.237525] CliCommunicator.vala:102: lid_close_dock:ignore
[DEBUG 16:30:23.237570] CliCommunicator.vala:107: lid_close:suspend
[DEBUG 16:30:23.250464] PlugsManager.vala:91: system-pantheon-power registered
[DEBUG 16:30:23.256018] Plug.vala:199: Activating Printers plug
[DEBUG 16:30:23.256110] PlugsManager.vala:91: pantheon-printers registered
[DEBUG 16:30:23.256722] BluetoothPlug.vala:103: Activating Bluetooth plug
[DEBUG 16:30:23.256771] PlugsManager.vala:91: network-gcc-bluetooth registered
[DEBUG 16:30:23.258073] Plug.vala:207: Activating Network plug
[DEBUG 16:30:23.293953] Settings.vala:163: Loading settings from schema 'org.gnome.system.proxy'
[DEBUG 16:30:23.294302] Settings.vala:163: Loading settings from schema 'org.gnome.system.proxy.ftp'
[DEBUG 16:30:23.294454] Settings.vala:163: Loading settings from schema 'org.gnome.system.proxy.http'
[DEBUG 16:30:23.294593] Settings.vala:163: Loading settings from schema 'org.gnome.system.proxy.https'
[DEBUG 16:30:23.294742] Settings.vala:163: Loading settings from schema 'org.gnome.system.proxy.socks'
[DEBUG 16:30:23.294896] PlugsManager.vala:91: pantheon-network registered
[DEBUG 16:30:23.314435] OnlineAccounts.vala:290: Activating Online Accounts plug
[DEBUG 16:30:23.314920] LastFM.vala:41: OnlineAccouts: Activating LastFM plugin
[DEBUG 16:30:23.315236] Email.vala:42: OnlineAccouts: Activating Mail plugin
[DEBUG 16:30:23.315505] fastmail.vala:42: OnlineAccouts: Activating FastMail plugin
[DEBUG 16:30:23.315755] Password.vala:41: OnlineAccouts: Activating Password plugin
[DEBUG 16:30:23.316571] PlugsManager.vala:91: network-pantheon-online-accounts registered
[DEBUG 16:30:23.317119] Plug.vala:123: Activating Sharing plug
[DEBUG 16:30:23.317180] PlugsManager.vala:91: pantheon-sharing registered
[DEBUG 16:30:23.317805] Plug.vala:109: Activating Applications plug
[DEBUG 16:30:23.317886] PlugsManager.vala:91: personal-pantheon-applications registered
[DEBUG 16:30:23.319039] desktop-plug.vala:178: Activating Desktop plug
[DEBUG 16:30:23.319102] PlugsManager.vala:91: pantheon-desktop registered
[DEBUG 16:30:23.319941] Plug.vala:193: Activating Locale plug
[DEBUG 16:30:23.320005] PlugsManager.vala:91: system-pantheon-locale registered
[DEBUG 16:30:23.320545] Plug.vala:91: Activating Notifications plug
[DEBUG 16:30:23.320606] PlugsManager.vala:91: personal-pantheon-notifications registered
[DEBUG 16:30:23.321220] Plug.vala:127: Activating Security & Privacy plug
[DEBUG 16:30:23.321279] PlugsManager.vala:91: pantheon-security-privacy registered
[INFO 16:30:23.322088] Tweaks.vala:307: Activating Tweak plug
[WARNING 16:30:23.327682] GtkSettings.vala:48: Error loading GTK+ Keyfile settings.ini: No such file or directory
[WARNING 16:30:23.327710] GtkSettings.vala:69: Error getting GTK+ int setting: Key file does not have group 'Settings'
[DEBUG 16:30:23.329321] Settings.vala:163: Loading settings from schema 'org.gnome.desktop.wm.preferences'
[DEBUG 16:30:23.330948] Settings.vala:163: Loading settings from schema 'org.gnome.desktop.interface'
[DEBUG 16:30:23.353443] Settings.vala:163: Loading settings from schema 'org.pantheon.desktop.gala.appearance'
[DEBUG 16:30:23.387145] Settings.vala:163: Loading settings from schema 'org.pantheon.desktop.gala.animations'
[DEBUG 16:30:23.392118] Settings.vala:163: Loading settings from schema 'org.pantheon.desktop.gala.shadows'
[DEBUG 16:30:23.398128] Settings.vala:163: Loading settings from schema 'org.pantheon.elementary-tweaks.egtk'
[DEBUG 16:30:23.402321] Settings.vala:163: Loading settings from schema 'org.pantheon.files.preferences'
[DEBUG 16:30:23.405599] Settings.vala:163: Loading settings from schema 'org.pantheon.desktop.slingshot'
[DEBUG 16:30:23.407286] Settings.vala:163: Loading settings from schema 'org.pantheon.terminal.settings'
[ERROR 16:30:23.407421] [GLib-GIO] Settings schema 'org.pantheon.terminal.settings' does not contain a key named 'opacity'
Trace/breakpoint trap (core dumped)

**Comment by Philip-Scott** [comment]
You've installed the Freya (and broken) version of elementary tweaks :wink: 
https://github.com/elementary-tweaks/elementary-tweaks/issues/18

Remove the ppa you added, and install the one from this repo :)

**Comment by pedrotarazi** [comment]
Thanks for answering. I did that, and I still have the same problem. 

![screenshot from 2016-11-20 19 45 42](https://cloud.githubusercontent.com/assets/16615951/20466871/014f629c-af5a-11e6-950d-7098bb0977c2.png)
![screenshot from 2016-11-20 19 46 03](https://cloud.githubusercontent.com/assets/16615951/20466872/04ed7c68-af5a-11e6-8892-9694aa70de07.png)

**Comment by Philip-Scott** [comment]
Looks like you still have the i-hate-farms ppa. You need to remove that ppa, then purge elementary-tweaks and re-install it :)
