### ISSUE TITLE
Restore old icon for animation

### ISSUE THREAD

**Issue by varlesh** [elementary-tweaks/elementary-tweaks#38]
Now use  icon **go-jump** for Animations category:
```
 public AnimationsPane () {
            base (_("Animations"), "go-jump");
        }
```
It's not good, because it's "actions" icon. Better restore old version **preferences-tweaks-anim**

Also will be good if you add option for disable/enable animation on wingpanel (gnome animations):
```
org.gnome.desktop.interface enable-animations
```

**Comment by Philip-Scott** [comment]
I think i will restore the old icon, but i won't be adding the enable-animations option since it breaks things with Gtk.Revealers (Wingpanel uses them for example)
