### ISSUE TITLE
Cannot install ET with this PPA

### ISSUE THREAD

**Issue by srsohn711** [elementary-tweaks/elementary-tweaks#39]
Tried several different ways and times to install ET and have not been successful. I have used terminal and added the PPA. I have used git. No matter what I do I get the same thing. 

This is what I get after `sudo apt-get update` then I do `sudo apt-get install elementary-tweaks` 

`Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package elementary-tweaks
` 

I am not sure of what else to do.. Any help would be appreciated..

**Comment by Philip-Scott** [comment]
You did add this ppa, right? 

`sudo add-apt-repository ppa:philip.scott/elementary-tweaks`

**Comment by srsohn711** [comment]
Yes used that PPA.. 

I have tried it and purged it and tried it again and again.

Trying once more right now.. Will update with results.

**Comment by srsohn711** [comment]
This is what was at the end after `sudo apt-get update` 

W: The repository 'http://archive.canonical.com loki Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://security.ubuntu.com/ubuntu loki-security Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://ppa.launchpad.net/elementary-os/stable/ubuntu loki Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://ppa.launchpad.net/elementary-os/os-patches/ubuntu loki Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu zesty Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://us.archive.ubuntu.com/ubuntu loki Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://us.archive.ubuntu.com/ubuntu loki-updates Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://us.archive.ubuntu.com/ubuntu loki-backports Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://archive.canonical.com/dists/loki/partner/binary-amd64/Packages  404  Not Found [IP: 91.189.92.191 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/loki-security/main/binary-amd64/Packages  404  Not Found [IP: 91.189.91.26 80]
E: Failed to fetch http://ppa.launchpad.net/elementary-os/stable/ubuntu/dists/loki/main/source/Sources  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/elementary-os/os-patches/ubuntu/dists/loki/main/source/Sources  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu/dists/zesty/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/loki/main/binary-amd64/Packages  404  Not Found [IP: 91.189.91.23 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/loki-updates/main/binary-amd64/Packages  404  Not Found [IP: 91.189.91.23 80]
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/loki-backports/main/binary-amd64/Packages  404  Not Found [IP: 91.189.91.23 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by srsohn711** [comment]
After trying to install again using:
`sudo apt-get install elementary-tweaks` 

I am still getting the same error:

`Reading package lists... Done`
`Building dependency tree  `     
`Reading state information... Done`
`E: Unable to locate package elementary-tweaks`

**Comment by Philip-Scott** [comment]
Looks like you have much bigger problems, not just with this PPA. What happens if you try to install anything else from the command line?

**Comment by srsohn711** [comment]
I still get the 404s but am able to install things.. 

Such as gdebi and kodi I installed afterward.

If anything I will remove the partition and then redo Loki all together and see if that fixes it.

**Comment by Philip-Scott** [comment]
It looks very weird that it says Loki instead of xenial. Let me ask the elementary team about it before you do anything (I'm not near My PC ATM to check it myself)

**Comment by srsohn711** [comment]
Ok did a fresh install and it works... 

I am not sure what was happening.. 

I did not see your above message until after install..

Thanks for all the help.

**Comment by Philip-Scott** [comment]
Glad you were able to solve it :)

**Comment by png2378** [comment]
Maybe this solution will be helpful to others: 

`sudo sed -i 's/loki/xenial/g' /etc/apt/sources.list.d/*.list`
