### ISSUE TITLE
how to change font size of terminal

### ISSUE THREAD

**Issue by yanglimingchn** [elementary-tweaks/elementary-tweaks#40]
How to change font size of terminal, if can not now, can you please add this feature

**Comment by ryonakano** [comment]
![screenshot from 2018-07-27 21-42-52](https://user-images.githubusercontent.com/26003928/43321252-3213e3ce-91e6-11e8-933c-88867369d929.png)

I don't think we have to add this option to elementary-tweaks since it will be supported officially in Juno.

**Comment by Philip-Scott** [comment]
I'm happy to see that we're slowly closing all these issues by not coding them in elementary Tweaks but by adding them as features in elementary :)
