### ISSUE TITLE
Desktop icons

### ISSUE THREAD

**Issue by codecowboy** [elementary-tweaks/elementary-tweaks#45]
Is there a tweak available for restoring desktop icons for the Desktop folder? I know this was a design decision by the elementary team but I'd like to enable it. I am aware there is a way of doing this via dconf editor but the dconf editor icon offends me :)

**Comment by Philip-Scott** [comment]
Actually, on elementary there is just no code for using desktop icons. People use a whole separate app for it so it's not something that can be enabled with a single switch :/ 

This _might_ work for you: https://elementaryos.stackexchange.com/questions/3856/how-to-enable-desktop-icons-and-right-click-in-elementary-os-freya :)
