### ISSUE TITLE
 'org.pantheon.desktop.slingshot' does not contain a key named 'show-category-filter': Switchboard crashes on click of Tweaks

### ISSUE THREAD

**Issue by worldofpeace** [elementary-tweaks/elementary-tweaks#49]
Kernel: 4.11.1-041101-generic x86_64
GTK+: 3.18.9
Distro: elementary 0.4.1 loki
Switchboard Version: 2.0
I am on the daily ppa

### Steps to reproduce
1. Open switchboard
2. Click on Tweaks
3. **App Crashes** 

We already know what's expected.

### What's displayed in the Terminal upon click:
Loading settings from schema 'org.gnome.desktop.interface'
GalaSettings.vala:115: Adding button layout: :minimize,maximize,close => Windows
Settings.vala:163: Loading settings from schema 'org.pantheon.desktop.gala.appearance'
GalaSettings.vala:115: Adding button layout: close:maximize => elementary
GalaSettings.vala:115: Adding button layout: close:minimize,maximize => Minimize Right
GalaSettings.vala:115: Adding button layout: close,minimize,maximize => OS X
GalaSettings.vala:115: Adding button layout: close,minimize:maximize => Minimize Left
GalaSettings.vala:115: Adding button layout: :close => Close Only Right
GalaSettings.vala:115: Adding button layout: close: => Close Only Left
[Gtk] gtk_combo_box_set_model: assertion 'GTK_IS_COMBO_BOX (combo_box)' failed
Settings.vala:163: Loading settings from schema 'org.gnome.desktop.wm.preferences'
Settings.vala:163: Loading settings from schema 'org.pantheon.desktop.gala.animations'
Max volume: 100
FilesSettings.vala:53: Adding button layout: iso => ISO
Settings.vala:163: Loading settings from schema 'org.pantheon.files.preferences'
FilesSettings.vala:53: Adding button layout: locale => Locale
FilesSettings.vala:53: Adding button layout: informal => Informal
FilesSettings.vala:53: Adding button layout: iso => ISO
FilesSettings.vala:53: Adding button layout: locale => Locale
FilesSettings.vala:53: Adding button layout: informal => Informal
Settings.vala:163: Loading settings from schema 'org.pantheon.desktop.slingshot'
[Error] [GLib-GIO] Settings schema 'org.pantheon.desktop.slingshot' does not contain a key named 'show-category-filter'

### My guess
This has something to do with it https://github.com/elementary/applications-menu/commit/e391672b90ba870a61997d82458e9c97003f04a1

**Comment by worldofpeace** [comment]
You can fix this for now by downgrading slingshot-launcher to 2.1.3+r775+pkg70~daily~ubuntu0.4.1

**Comment by Philip-Scott** [comment]
Yup, that's definitely what broke it. I'll be pushing an update for tweaks soon

**Comment by Philip-Scott** [comment]
A new version is currently being built. Thanks for reporting it!

**Comment by worldofpeace** [comment]
You're very welcome. :+1:
