### ISSUE TITLE
CMake Error: The source directory "/home/integral/build" does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by IntegralWorks** [elementary-tweaks/elementary-tweaks#50]
I followed the instructions on README.md. But during

`sudo apt-get install libgconf2-dev libpolkit-gobject-1-dev libswitchboard-2.0-dev elementary-sdk`

`mkdir build`
`cd build`
`cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr/ `

I get the following error:
 `CMake Error: The source directory "/home/integral/build" does not appear to contain CMakeLists.txt.`

EDIT: So I have no idea why, but after I restarting my computer flux is working seamlessly, GUI and all.

**Comment by embik** [comment]
You need to clone this repository and create the `build` directory _inside_ the cloned repository. If you don't have an idea how that works, for your own sake, stick to using the [official PPA](https://github.com/elementary-tweaks/elementary-tweaks#installation) and do not try to build from source.
