### ISSUE TITLE
[Feature Request] Always on top

### ISSUE THREAD

**Issue by JustABanana** [elementary-tweaks/elementary-tweaks#51]
In gnome there is an option that allows you to set window almost on top and it's a really usefull feature. Is it possible to add?

**Comment by JustABanana** [comment]
Just wanted to add that I know that there is an option to bind this to a button combination but it's really unintuitive and right clicking window to turn this on/off would be way better

**Comment by Philip-Scott** [comment]
You can already do so from within the Keyboard settings :) ![screenshot from 2017-06-05 07 47 24](https://cloud.githubusercontent.com/assets/10786508/26784457/93c20bdc-49b2-11e7-9e4f-cc9f229cad7d.png)
