### ISSUE TITLE
No Tweaks Under Files Tab and Terminal Tab

### ISSUE THREAD

**Issue by worldofpeace** [elementary-tweaks/elementary-tweaks#56]
![image](https://user-images.githubusercontent.com/28888242/30761110-0cf3d320-9fab-11e7-9cae-9d71b31ccc51.png)
![image](https://user-images.githubusercontent.com/28888242/30761136-2a8b1f9c-9fab-11e7-8fd6-c3eb153b7872.png)
The paths changed recently right? I'm using the daily ppa.

**Comment by Mierscheid** [comment]
Same problem here...

**Comment by codercv** [comment]
Same problem here...
