### ISSUE TITLE
Launcher

### ISSUE THREAD

**Issue by rodgerbarker** [elementary-tweaks/elementary-tweaks#59]
Launcher is a great idea,BUT! Every time I change the size of the matrix, usually to 5 columns and 3 rows, it automatically changes back to the default 3 by 3. Is it possible to fix it on the revised matrix size?
Many thanks

**Comment by dalbinaco** [comment]
Same problem here.

**Comment by ryonakano** [comment]
We can close this issue because we don't have this option anymore (see #116).
