### ISSUE TITLE
Middle-click Paste enable / disable option

### ISSUE THREAD

**Issue by peteruithoven** [elementary-tweaks/elementary-tweaks#60]
I'd love a Middle-click Paste enable / disable option in Elementary Tweaks, just like the Gnome Tweak tool.

**Comment by ryonakano** [comment]
Since this option is [officially supported](https://github.com/elementary/switchboard-plug-mouse-touchpad/pull/24), I think we don't have to add this option in elementary-tweaks, IMO.

**Comment by Philip-Scott** [comment]
Good catch @ryonakano! I'll close this then
