### ISSUE TITLE
Moving polkit-gobject-1 to its own repository?

### ISSUE THREAD

**Issue by kirbyfan64** [elementary-tweaks/elementary-tweaks#64]
I've recently taken up writing an application in Vala, and right now I just copy-pasted `polkit-gobject-1.vapi` to my project. However, considering that there I couldn't locate any other polkit bindings for Vala, it would be nice if that were in a separate repository, making it easier for others to use.

**Comment by mdh34** [comment]
I believe that the polkit-gobject-1 bindings are now included in vala as of valac 0.34.1 so you shouldn't need a .vapi for them

**Comment by kirbyfan64** [comment]
Hmm, you're right. Not sure how I didn't notice this... Sorry for the noise!
