### ISSUE TITLE
Any way i can compile this on fedora 28?

### ISSUE THREAD

**Issue by surajmandalcell** [elementary-tweaks/elementary-tweaks#75]
I've been using pantheon desktop with fedora for a while now and it'd be nice to have elementary-tweaks installed there. The problem is that all of the dependencies mentioned (libgconf2-dev libpolkit-gobject-1-dev libswitchboard-2.0-dev elementary-sdk) can't be installed in fedora (dunno what the names are in fedora and cant find elementary-sdk rpm).
Please help!

**Comment by elektronen** [comment]
Hey! Yes! See my write-up on this at http://bytebitez.blogspot.com/2018/02/how-to-build-elementary-tweaks-on.html (written for F27, but I just used it on F29 without any issues)

**Comment by Philip-Scott** [comment]
Thank you, elektronen :)
