### ISSUE TITLE
Figure out how to publish packages

### ISSUE THREAD

**Issue by embik** [elementary-tweaks/elementary-tweaks#8]
This is an issue to track information and research concerning how to publish our packages. Here's a list of things we need and possible choices:

* a GPG key to sign the packages
  * generate a new key and sign it with [my key](https://keybase.io/embik)
* a tool to build the repository metadata
  * [aptly](http://www.aptly.info/)
  * reprepro (German tutorials: [#1](https://wiki.ubuntuusers.de/reprepro/), [#2](https://www.thomas-krenn.com/de/wiki/Eigenes_apt-Repository_mit_reprepro_unter_Ubuntu_erstellen), Debian tutorials: [#1](https://wiki.debian.org/SettingUpSignedAptRepositoryWithReprepro))
* webspace to upload the repository to
  * GitHub Pages
     * git isn't exactly made for deb archieves, neither is GitHub Pages. But it's free HTTP and we will produce very small traffic in comparison to other projects on GH
  * my personal website
     * has unlimited bandwith, but I'm not sure how much CPU/RAM load the elementary community will produce on it. It's a very small server (2 Cores, 6 GB RAM) after all
  * a third-party debian package hoster
    * [bintray](https://bintray.com/)

**Comment by Philip-Scott** [comment]
I've got it hosted and installable under [my own PPA](https://launchpad.net/~philip.scott/+archive/ubuntu/elementary-tweaks) atm and i've just emailed the old maintainer of https://launchpad.net/elementary-tweaks to see if he could make me the new maintainer so I could use the old PPA instead. 

If we really need a website, i think github pages will do :smile:
