### ISSUE TITLE
Feature request: option to change the default 'Files' landing path

### ISSUE THREAD

**Issue by derkomai** [elementary-tweaks/elementary-tweaks#84]
When Files is opened or a new tab is invoked, the actual path will be set to /home/username. It would be nice to be able to change this behavior and set the landing path to the one that suits the user the most, i.e. /home/username/Downloads.

**Comment by Philip-Scott** [comment]
Files does not have this feature as it always opens by default the user's home directory, or the last opened folder. Sorry, this is not something elementary Tweaks can do
