### ISSUE TITLE
_elementary_tweaks_categories___lambda23_(): Switchboard crashes on window close

### ISSUE THREAD

**Issue by embik** [elementary-tweaks/elementary-tweaks#9]
Sometimes (I cannot reproduce this in a reliable way currently) tweaks is crashing Switchboard when closing the window on Freya.

![switchboard_crash](https://cloud.githubusercontent.com/assets/10295525/14077380/2e846570-f4eb-11e5-800b-a7a72e7d2f4f.png)

Unfortunately I have very little idea what lambda function could be crashing.

**Comment by Philip-Scott** [comment]
Can confirm, just opening the plug and closing switchboard crashes here on loki

**Comment by Philip-Scott** [comment]
I meant to push it to a different branch.... but the newest commit should fix it :)
