### ISSUE TITLE
Workspace number indicator 

### ISSUE THREAD

**Issue by jchannon** [elementary-tweaks/elementary-tweaks#92]
Is there way on the taskbar to show what number the current workspace the user is on? I found a plug-in that is 4 years old and designed to work on an older elementary.

Would be good if the tweaks project could highlight what workspace number the user is currently on

**Comment by Hedronmx** [comment]
Could you link to the software you are using?

**Comment by Dirli** [comment]
You can try this one, but until static desktops are implemented, it will only work dynamically, navigation available. Test at the same time)))
https://github.com/Dirli/wingpanel-indicator-workspaces

**Comment by Philip-Scott** [comment]
Thank your for the suggestion, but this is currently out of scope for this project.
