### ISSUE TITLE
Launcher is 1-column less than indicated on Tweaks, even after reboot

### ISSUE THREAD

**Issue by sprite-1** [elementary-tweaks/elementary-tweaks#96]
![image](https://user-images.githubusercontent.com/33685433/51593220-94624100-1f2c-11e9-93f0-07a3740ca7b9.png)

When I set the column count to 5, it will go ahead and show 5 columns for the session but when I reboot, it's going to have 4 columns.

If I then set it to 4 columns and restart, it's going to show up as the screenshot above with just 3 columns shown.

**Comment by ryonakano** [comment]
We can close this issue because we don't have this option anymore (see #116).
